[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "postout"
version = "1.0.0"
license = { file = "LICENSE" }
description = "A simple, script-friendly SMTP command-line mailer"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Communications :: Email",
    "Topic :: System :: Systems Administration",
]

[project.scripts]
postout = "postout.cli:entrypoint"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
